# Generated by Django 5.2.1 on 2025-05-27 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Dish'),
        ),
        migrations.AlterField(
            model_name='eatingitem',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Available'),
        ),
        migrations.AlterField(
            model_name='eatingitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eating_item', to='main.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='eatingitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='eatingitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='eatingitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='eatingitem',
            name='dish_types',
            field=models.ManyToManyField(blank=True, related_name='eating_items', to='main.dishtype', verbose_name='Dish types'),
        ),
        migrations.AlterField(
            model_name='eatingitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='product/%Y/%m/%d', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='eatingitem',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='eatingitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='eatingitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='eatingitemdish',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Available'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='product/%Y/%m/%d', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.eatingitem', verbose_name='Product'),
        ),
    ]
