# Generated by Django 5.2.1 on 2025-05-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='type',
        ),
        migrations.AddField(
            model_name='dish',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='dishes', to='main.dishtype'),
        ),
        migrations.AlterField(
            model_name='dishtype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Dish type'),
        ),
    ]
