# Generated by Django 5.2.1 on 2025-05-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_dish_type_dish_types_alter_dishtype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='eatingitem',
            name='dish_types',
            field=models.ManyToManyField(blank=True, related_name='eating_items', to='main.dishtype'),
        ),
    ]
