# Generated by Django 5.2.1 on 2025-05-29 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_eatingitem_dish_types_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eatingitem',
            name='dish_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.dishtype'),
        ),
    ]
