# Generated by Django 5.2.1 on 2025-05-13 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_eatingitem_dish_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='types',
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='main.dishtype'),
        ),
    ]
