# Generated by Django 5.2.1 on 2025-05-29 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_eatingitem_dish_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eatingitem',
            old_name='dish_type',
            new_name='dish_types',
        ),
    ]
