# Generated by Django 5.2.1 on 2025-05-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_dish_types_dish_dish_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='dish_type',
        ),
        migrations.AddField(
            model_name='dish',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='dishes', to='main.dishtype'),
        ),
    ]
