# Generated by Django 5.2.1 on 2025-05-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_dish_type_eatingitem_dish_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eatingitem',
            old_name='dish_types',
            new_name='type_ids',
        ),
    ]
