# Generated by Django 5.2.1 on 2025-05-13 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_dish_dish_type_dish_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='types',
            new_name='dish_types',
        ),
    ]
