# Generated by Django 5.2.1 on 2025-05-13 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_types_dish_dish_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='dish_types',
            new_name='dish_type',
        ),
    ]
