# Generated by Django 5.2.1 on 2025-05-29 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_dish_types_eatingitem_type_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eatingitem',
            old_name='type_ids',
            new_name='dish_types',
        ),
    ]
