# Generated by Django 5.2.1 on 2025-05-29 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_type_ids_eatingitem_dish_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eatingitem',
            old_name='dish_types',
            new_name='types',
        ),
    ]
