# Generated by Django 5.2.1 on 2025-05-29 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_dish_types_eatingitem_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eatingitem',
            name='types',
        ),
        migrations.AddField(
            model_name='eatingitem',
            name='dish_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.dishtype'),
            preserve_default=False,
        ),
    ]
