# Generated by Django 5.2.1 on 2025-05-29 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_productset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSet',
        ),
    ]
