# Generated by Django 5.2.1 on 2025-05-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_delete_productset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eatingitem',
            name='dish_type',
        ),
        migrations.AddField(
            model_name='eatingitem',
            name='dish_types',
            field=models.ManyToManyField(blank=True, related_name='eating_items', to='main.dishtype'),
        ),
    ]
